version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    env_file: ./.env
    container_name: app-postgres
    environment:
      - POSTGRES_PASSWORD=$DB_USER
      - POSTGRES_USER=$DB_PASSWORD
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - $DB_PORT_LOCAL:$DB_PORT_DOCKER
  app:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: ./.env
volumes:
  postgres:
